-- =============================================================
-- bootstrap_dev.sql
-- One-time script to clone PROD into DEV.
-- Safe to re-run: uses CREATE ... IF NOT EXISTS where possible.
-- Does NOT touch any PROD objects.
-- =============================================================

USE ROLE SALES_ENGINEER;
USE WAREHOUSE COCO_PARTNER_ADOPTION_WH;

-- 1. Clone entire PROD schema into DEV (zero-copy, instant)
CREATE SCHEMA IF NOT EXISTS TEMP.COCO_PARTNER_ADOPTION_DEV
    CLONE TEMP.COCO_PARTNER_ADOPTION;

-- 2. Create DEV stages (not carried over by schema clone for internal stages)
CREATE STAGE IF NOT EXISTS TEMP.COCO_PARTNER_ADOPTION_DEV.STREAMLIT;
CREATE STAGE IF NOT EXISTS TEMP.COCO_PARTNER_ADOPTION_DEV.SV_STAGE;

-- 3. Suspend DEV task immediately — must never auto-run in DEV
ALTER TASK IF EXISTS TEMP.COCO_PARTNER_ADOPTION_DEV.TASK_REFRESH_TABLES SUSPEND;

-- 4. Create DT_OKR_USE_CASES dynamic table manually
--    NOTE: Snowflake schema clone does NOT carry over Dynamic Tables — must be created explicitly.
CREATE OR REPLACE DYNAMIC TABLE TEMP.COCO_PARTNER_ADOPTION_DEV.DT_OKR_USE_CASES
    LAG = '1 day'
    REFRESH_MODE = 'AUTO'
    INITIALIZE = 'ON_CREATE'
    WAREHOUSE = COCO_PARTNER_ADOPTION_WH
AS
WITH hierarchy AS (
    SELECT PARTNER_NAME, PARENT_PARTNER_NAME
    FROM TEMP.COCO_PARTNER_ADOPTION_DEV.PARTNER_HIERARCHY
),
stage_days AS (
    SELECT USE_CASE_ID, DATEDIFF('day', MOVEIN_DATE, CURRENT_DATE()) AS DAYS_IN_CURRENT_STAGE
    FROM MDM.MDM_INTERFACES.FACT_USE_CASE_STAGE_MOVEMENT
    QUALIFY ROW_NUMBER() OVER (PARTITION BY USE_CASE_ID ORDER BY MOVEIN_DATE DESC) = 1
)
SELECT
    COALESCE(h.PARENT_PARTNER_NAME,
        NULLIF(ARRAY_TO_STRING(UC.IMPLEMENTATION_SERVICES_PARTNER, ', '), '')
    ) AS PARTNER_NAME,
    NULLIF(ARRAY_TO_STRING(UC.IMPLEMENTATION_SERVICES_PARTNER, ', '), '') AS RAW_PARTNER_NAME,
    UC.USE_CASE_ID, UC.USE_CASE_NUMBER, UC.USE_CASE_NAME, UC.ACCOUNT_NAME, UC.USE_CASE_STAGE,
    UC.USE_CASE_EACV, UC.TECHNICAL_USE_CASE, UC.THEATER_NAME, UC.REGION_NAME,
    UC.DECISION_DATE, UC.GO_LIVE_DATE, UC.DAYS_IN_STAGE,
    COALESCE(sd.DAYS_IN_CURRENT_STAGE, UC.DAYS_IN_STAGE) AS DAYS_IN_CURRENT_STAGE,
    UC.WORKLOADS, UC.COMPETITORS, UC.ACCOUNT_LEAD_SE_NAME, UC.ACCOUNT_GVP,
    CASE
        WHEN UC.SE_COMMENTS ILIKE '%coco%' OR UC.SE_COMMENTS ILIKE '%cortex code%'
            OR UC.PARTNER_COMMENTS ILIKE '%#coco%'
            OR UC.PRIORITIZED_FEATURES ILIKE '%AI - Cortex Code%' THEN TRUE
        ELSE FALSE
    END AS IS_COCO,
    CASE
        WHEN UC.PARTNER_COMMENTS ILIKE '%#coco%' THEN 'PARTNER_COMMENTS'
        WHEN UC.SE_COMMENTS ILIKE '%coco%' OR UC.SE_COMMENTS ILIKE '%cortex code%' THEN 'SE_COMMENTS'
        WHEN UC.PRIORITIZED_FEATURES ILIKE '%AI - Cortex Code%' THEN 'FEATURE_FLAG'
        ELSE NULL
    END AS COCO_SOURCE
FROM MDM.MDM_INTERFACES.DIM_USE_CASE UC
LEFT JOIN hierarchy h
    ON NULLIF(ARRAY_TO_STRING(UC.IMPLEMENTATION_SERVICES_PARTNER, ', '), '') = h.PARTNER_NAME
LEFT JOIN stage_days sd ON UC.USE_CASE_ID = sd.USE_CASE_ID
WHERE UC.USE_CASE_STAGE IN (
    '3 - Technical / Business Validation', '4 - Use Case Won / Migration Plan',
    '5 - Implementation In Progress', '6 - Implementation Complete', '7 - Deployed'
)
AND NULLIF(ARRAY_TO_STRING(UC.IMPLEMENTATION_SERVICES_PARTNER, ', '), '') IS NOT NULL
AND COALESCE(h.PARENT_PARTNER_NAME, NULLIF(ARRAY_TO_STRING(UC.IMPLEMENTATION_SERVICES_PARTNER, ', '), ''))
    NOT IN ('Sigma Computing, Inc.', 'Bloomberg Finance L.P. - DCP Account');

-- 5. Confirm DEV task is suspended (verify output shows state = suspended)
SHOW TASKS IN SCHEMA TEMP.COCO_PARTNER_ADOPTION_DEV;

-- 5. Confirm PROD task state is unchanged
SHOW TASKS IN SCHEMA TEMP.COCO_PARTNER_ADOPTION;
