ENV = "prod"

[connections.snowflake]
account = "SFCOGSOPS-SNOWHOUSE_AWS_US_WEST_2"
user = "NIRASHAH"
authenticator = "externalbrowser"
role = "SALES_ENGINEER"
warehouse = "COCO_PARTNER_ADOPTION_WH"
database = "TEMP"
schema = "COCO_PARTNER_ADOPTION"
